baseURL = 'https://ahmadessamdev.xyz'
languageCode = 'en-us'
title = 'Ahmad Essam'
theme = "m10c"

[params]
  author = "Ahmad Essam"
  description = "Sofware Engineer trying to make better software!"
  menu_item_separator = " - "
  avatar = "images/myphoto.png"
  custom_css = "css/custom.css"
  favicon="favicon.ico"
  

[services]
  [services.disqus]
    shortname = 'ahmedspace-com'


  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ahmadessamdev"

  [[params.social]]
    icon = "stackoverflow"
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/2760325/ahmad-essam"

  [[params.social]]
    icon = "medium"
    name = "medium"
    url = "https://ahmadessamdev.medium.com"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/ahmadessamdev"


[menu]

  [[menu.main]]
  identifier = "mywork"
  name = "My Work"
  weight = 1
  title= "My Work"
  url = "/mywork/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  weight = 3
  url = "/tags/"
